### ISSUE TITLE
POST error

### ISSUE THREAD

**Issue by dontbanmeplz** [ken107/ttstool.com#4]
when i run `curl -XPOST -H 'Accept: */*' -H "Content-type: application/json" -d '{"voiceId":"Amazon British English (Brian)","ssml":"<speak version=\"1.0\" xml:lang=\"en-GB\">Hello</speak>"}' 'https://support.readaloud.app/ttstool/createParts'`
I get the responce
`TypeError: parts.reduce is not a function<br> &nbsp; &nbsp;at Object.exports.create (/home/ec2-user/webservices/dist/read-aloud/parts.js:18:25)<br> &nbsp; &nbsp;at createParts (/home/ec2-user/webservices/dist/ttstool/index.js:36:9)<br> &nbsp; &nbsp;at Layer.` What am i doing wrong

**Comment by BopItFreak** [comment]
you have to use double quotes and escape the other double quotes
